### ISSUE TITLE
PrintReg assertion failure for microop `vclear`

### ISSUE THREAD

**Issue by jyhuang91** [seanzw/gem5-avx#1]
I was running an AVX2 code with `VXORPD_XMM_XMM` instruction with O3CPUAll debug flag on to trace the pipeline execution. And I hit an assertion failure at here (in `X86StaticInst::printReg`):
https://github.com/seanzw/gem5-avx/blob/c5aa96a71b4929692d6efd1d0878dacbe2131a07/src/arch/x86/insts/static_inst.cc#L125-L126

I noticed that this instruction is decoded to three microops including the [`vclear`](https://github.com/seanzw/gem5-avx/blob/avx/src/arch/x86/isa/insts/simd512/floating_point/arithmetic/vxorpd.py#L6) microop to clear the higher bits. The assertion failure is caused by the `vclear` due to the destSize is 0 (which is not assigned in the microop).

The calling path is as follows:
[`disassemble(thisPC.instAddr())`](https://github.com/seanzw/gem5-avx/blob/avx/src/cpu/o3/fetch_impl.hh#L1085) -> [`generateDisassembly(pc, symtab)`](https://github.com/seanzw/gem5-avx/blob/avx/src/cpu/static_inst.cc#L119) -> [`printDestReg(response, 0, destSize);`](https://github.com/seanzw/gem5-avx/blob/avx/src/arch/x86/insts/microavxop.cc#L15) -> [`printReg(os, destRegIdx(reg), size);`](https://github.com/seanzw/gem5-avx/blob/avx/src/arch/x86/insts/static_inst.cc#L117) -> [`assert(...);`](https://github.com/seanzw/gem5-avx/blob/avx/src/arch/x86/insts/static_inst.cc#L125-L126)

I wondered if I am doing the right thing? If so, whether the assertion condition should be changed, or the [`vclear`](https://github.com/seanzw/gem5-avx/blob/avx/src/arch/x86/isa/microops/avxop.isa#L171-L177) microop and the [`macroop to microop conversion`](https://github.com/seanzw/gem5-avx/blob/avx/src/arch/x86/isa/insts/simd512/floating_point/arithmetic/vxorpd.py#L6) should be updated?

**Comment by seanzw** [comment]
If the size is 0, which means `vclear` thinks there is no higher bits to clear. Here is the definition of [`vclear`](https://github.com/seanzw/gem5-avx/blob/avx/src/arch/x86/isa/microops/avxop.isa#L171-L195). It tries to clear bits until `NumXMMSubRegs`. Maybe you can add assertion here to check the value of this NumXMMSubRegs. With AVX512 this number should be 8, as 512bits = 8 * 64bits.

If there is indeed no higher bits to clear, `vclear` would just be a nop. You can simply modify the printReg() to print something reasonable. If you fixed this problem, I am happy to accept a pull request : )

**Comment by jyhuang91** [comment]
Thanks for the quick response.

I found that the `destSize` is 0 for all `vclear` since the microop only takes `destVL` (as shown in both the [definition](https://github.com/seanzw/gem5-avx/blob/avx/src/arch/x86/isa/microops/avxop.isa#L171-L195) and machine instruction to microop [decoding](https://github.com/seanzw/gem5-avx/blob/avx/src/arch/x86/isa/insts/simd512/floating_point/arithmetic/vaddpd.py#L3-L6), and `destSize` will take the default value 0. I wondered if `destSize` can be calculated from `destVL`: `destSize = 64 - destVL` (512bits = 64 bytes)?

Once I get things clear, I'd love to fix it and create a pull request :)

**Comment by seanzw** [comment]
I see. I misunderstood the problem. Now I can see what happened.

I think you are correct that `destSize = 64 - destVL`, which is the size of bytes `vclear` trying to clear. But I don't think the current `printReg()` can handle all the cases. For example if you want to clear the higher 48 bytes, then with `destSize = 64 - 16 = 48`. It still triggers the assertion as 48 destSize is not supported.

I think you can try compute `destSize = sizeof(uint64_t) * NumXMMSubRegs - destVL` in the constructor of `vclear` (I use NumXMMSubRegs to avoid the magic number of 64 bytes and in case we have AVX-1024 in the future lol). And in the `printReg()` relax the assertion to allow `destSize == 48`, and then it should be fine and print out something like `xmm0_2(48)` for you.

Funny that I never ran into this problem. I guess I never try to disassemble this instruction before : )

**Comment by jyhuang91** [comment]
There will be two ways to change it:
1. As you suggested, change that in the constructor of `vclear` by adding `destSize = sizeof(uint64_t) * NumXMMSubRegs - destVL`. This way also needs to change `const uint8_t destSize` to `uint8_t destSize`.
2. Another way is to add the destSize in the `vclear` in the isa files in [`src/arch/x86/isa/insts/simd512/floating_point/`](https://github.com/seanzw/gem5-avx/tree/avx/src/arch/x86/isa/insts/simd512/floating_point) and the constructor file accordingly. For example, change `vclear dest=xmm2, destVL=16` to `vclear dest=xmm2, destVL=16, destSize=48`, and
```
       def __init__(self, dest, destVL):
              super(Vclear, self).__init__(
                  dest=dest,
                  destVL=destVL,
              )
```
to
```
       def __init__(self, dest, destVL, destSize):
              super(Vclear, self).__init__(
                  dest=dest,
                  destVL=destVL,
                  destSize=destSize,
              )
```

Which way you think is better?

**Comment by seanzw** [comment]
I think we can take a hybrid approach here to avoid removing the constant and also avoid manually adding `destSize=48` to all `vclear` instructions. Let's compute `destSize` in the construction:

```python
        def __init__(self, dest, destVL):
              super(Vclear, self).__init__(
                  dest=dest,
                  destVL=destVL,
                  destSize=64 - destVL,
              )
```

The only drawback is that we don't have `NumXMMSubRegs` in the python constructor. But I think it's okay to assume that. And we can add this in the constructor code to check:

```python
     constructorCode = '''
            // Add MAXVL-1:VL to destination.
            auto vRegs = destVL / sizeof(uint64_t);
            assert(vRegs <= NumXMMSubRegs && "VL overflow.");
            assert(NumXMMSubRegs == 8 && "We assume 64-byte zmm registers.");
    """"
```

**Comment by jyhuang91** [comment]
Make sense. Let me test it and create a pull request.
